### ISSUE TITLE
Insert Citation Hides Markup

### ISSUE THREAD

**Issue by adam3smith** [zotero/zotero-word-for-windows-integration#19] opened 2015-10-16 15:16 UTC
https://forums.zotero.org/discussion/52639/force-close-of-all-markup/#Item_4

Any insert/edit citation action changes show changes setting to "No Markup".

**Comment by bwiernik** [comment] 2016-08-11 16:21
After https://github.com/zotero/zotero-word-for-windows-integration/commit/dc9e67fe7a3547def56b0efcb04544a1762ccbe5

changing a citation instead sets Markup to "Show All Changes". Instead, the function should store the current state and then restore it after inserting/editing the citation.

**Comment by bwiernik** [comment] 2017-03-24 14:08
Here is the VBA that we could use to store a document's revision status, then restore it after Zotero does its changes:

https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_windows8/how-to-change-simple-markup-in-word-2013-to-all/309b004e-d6bd-4716-9eee-3180ea496838

**Comment by adomasven** [comment] 2017-04-12 12:46
The revision status thing is a new change in Word 2013. If No Markup is selected then the setting remains unchanged. However, Simple Markup is always changed to All Markup.

The solution to this is not exactly trivial, because we would need to regenerate at least [CView0.h](https://github.com/zotero/zotero-word-for-windows-integration/blob/85c1f1cb4c790fee950cb62859c522a5e6f64c72/build/zoteroWinWordIntegration/CView0.h), which I currently have no idea how that's done or it's broken. Either way this is not as huge a problem as it was before dc9e67f

**Comment by adomasven** [comment] 2020-06-05 09:21
Although technically #56 is a duplicate of this issue, I now know how to regenerate the word header files and the newer issue has better description of the issue as well as a plan for solution, so closing this one.

**Closed by adomasven** 2020-06-05 09:21 UTC
