### ISSUE TITLE
Create separate section in the ribbon for Zotero buttons

### ISSUE THREAD

**Issue by simonster** [zotero/zotero-word-for-windows-integration#1] opened 2012-01-20 22:23 UTC
http://forums.zotero.org/discussion/21451/ms-word-plugin-can-we-have-zotero-menu-in-the-ribbon/

**Comment by jasonhansel** [comment] 2015-05-02 16:55
Has there been any work on this? Would be very useful.

**Comment by IllyaMoskvin** [comment] 2015-06-09 14:52
I'm reporting a small bug re: @marckl67's Zotero.dotm template: the macro defined in the ZoteroLib module cannot detect a Zotero field (citation) directly under the cursor when the cursor is in a footnote. I think the issue is with the *getZoteroFieldAtSelection* function, but I'm not familiar enough with Word and VBA to fix it within a reasonable time. 

For example, let's say you're using in-line citations for the document, but you need to occasionally insert footnotes (using Word's native *Insert Footnote* functionality), where you add aside comments on your main claims or some such. Then, say you need to insert in-line citations into these footnotes in order to back up these tangential claims. Inserting these in-line citations into the footnotes works just fine, but the *Insert Citation* button does not turn into *Edit Citation* when the text cursor is placed inside this citation. It does turn correctly, however, if you select text that includes all or part of the citation. This is very much an edge-case scenario, so I don't imagine most folks would ever run into this problem.

Thanks for the great plugin-template-thing!

**Comment by marckl67** [comment] 2015-06-09 20:53
IllyaMoskvin,
Thanks for your comment. I will have a look.

**Comment by bwiernik** [comment] 2015-06-09 21:01
This may be a wider issue with Word and Zotero fields in footnotes. Those citations in the footnotes don't show up in the bibliography (at least in the document I'm testing right now). 






On Tue, Jun 9, 2015 at 1:53 PM -0700, "marckl67" <notifications@github.com> wrote:












IllyaMoskvin,

Thanks for your comment. I will have a look.

**Comment by IllyaMoskvin** [comment] 2015-06-11 02:20
Thanks for the quick response! Again, I'm not familiar with Word macros or VBA, but I'll share the bits of research I did in trying to fix this problem myself. You are probably already aware of this info, but maybe it'll help somehow.

Basically, Word seems to store things in **Stories**. The story that stores the main document text is *wdMainTextStory*, which is separate from *wdFootnotesStory*, *wdPrimaryFooterStory*, *wdPrimaryHeaderStory*, and [others listed here](https://msdn.microsoft.com/en-us/library/office/ff844990.aspx). Stories present in the current document are stored in **ActiveDocument.StoryRanges** ([Office 2003](https://msdn.microsoft.com/en-us/library/office/aa223717(v=office.11).aspx), [Office 2010](https://msdn.microsoft.com/en-us/library/office/ff845743(v=office.14).aspx), [Office 2013](https://msdn.microsoft.com/en-us/library/office/ff845743.aspx)).

Just to provide some more code examples, here's a discussion re: [searching outside the main story](https://www.autoitscript.com/forum/topic/165384-wordau3-search-outside-the-main-body-of-the-word-doc/). Here's one re: [updating fields in all stories](http://www.wordbanter.com/showthread.php?t=105556), which links to [this article](http://www.gmayor.com/installing_macro.htm).

I'm guessing that when you call *Selection.Document.content*, it only accounts for content inside *wdMainTextStory*. So to detect citations in footnotes, you would have to loop through all the stories in the document, perhaps..? This might be inefficient, however. (Who puts citations in global headers or footers?!) So maybe adding a check for Zotero citations inside *wdFootnotesStory* specifically would suffice for fixing both the *Insert/Edit* button toggle macro and the bibliography generator.

I'm mostly guessing here, but I hope this helps a bit in resolving this problem. Cheers!

**Comment by IllyaMoskvin** [comment] 2015-06-11 02:42
On second thought, checking *wdEndnotesStory* might be a good idea, too. Also, I think updating (refreshing) in-line citations inside footnotes does indeed work correctly at the moment. At least, when I tried changing from an in-line citation format to one that requires footnotes or endnotes, existing in-line citations inside my footnotes changed format as expected.

Specifically, I used Chicago 16th edition, changing from *author-date* to *note* format. I wanted to see what would happen: would it generate additional footnotes, referencing them inside existing footnotes, where the in-line citations used to be? It did not generate additional footnotes, it just changed the format of the text inside the citation field.

As an aside, I wish there was a way to disable automatic parentheses around citations, just as there is a way to suppress author. For example, let's say that I'm referring to the cited article itself, rather than what the authors are saying: "For more info, see Smith 1998." AFAIK, this is currently not possible with Zotero. Apologies, I know this is unrelated.

**Comment by bwiernik** [comment] 2015-07-26 07:45
One other note about this code: As written, the individual Zotero macros (Add citation, Edit Citation, Refresh, etc.) are not exposed in the Word interface, so the user can't assign keyboard shortcuts to them. With the stock template, the user can assign arbitrary keyboard shortcuts to the Zotero macros in the Customize Ribbon menu. The Zotero macros should be included independently in the template code, even if they aren't used in the ribbon interface code.

**Comment by marckl67** [comment] 2015-07-31 15:51
@bwiernik 
Very good idea. The code has been modified to expose the individual Zotero macros.

**Closed** 2015-08-23 21:34 UTC
