### ISSUE TITLE
"no document is open" error if a Word document is stored in OneDrive

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-word-for-windows-integration#50] opened 2018-10-11 21:22 UTC
There've been a lot of reports of this. We probably can't do much about this, but we should at least try to reproduce it.

https://forums.zotero.org/discussion/73678/error-id-944178723/p1

**Comment by adomasven** [comment] 2018-10-15 11:07
This doesn't seem to be trivial to reproduce. I've played around with documents in OneDrive and they're working fine. I've also just received the newest update for Word, and assuming it's not only cosmetics that have been revamped, Microsoft may have fixed whatever was causing this in the latest version

**Comment by simonster** [comment] 2018-10-17 03:58
There are two ways the integration plug-in can try to find the Word document. The preferred way is to look up the document by name. If this doesn't work, it falls back to looking for the first document for an open Word instance.

It is possible that OneDrive makes the first approach fail. In this case, the second approach will still work as long as there's only one running Word instance. But IIRC it is possible for there to be multiple Word instances (I vaguely remember something about Outlook embedding Word here) and in this case the second approach may fail.

**Comment by adomasven** [comment] 2018-11-13 14:23
Thanks @simonster, your comment got me onto the right track to fixing this.

**Comment by adomasven** [comment] 2020-05-04 11:18
We have had reports of OneDrive documents failing for a while, but nobody managed to troubleshoot this for me successfully until [this post](https://forums.zotero.org/discussion/82933/found-a-workaround-for-zotero-experienced-an-error-updating-your-document-in-onedrive)

Will get around to fixing this at some point.

**Comment by adomasven** [comment] 2021-05-07 07:48
So we're still unable to get to the bottom of this, but a user posted another weird lead https://forums.zotero.org/discussion/comment/382417/#Comment_382417

**Comment by hoverdonkey** [comment] 2021-05-21 08:28
> 
> 
> So we're still unable to get to the bottom of this, but a user posted another weird lead https://forums.zotero.org/discussion/comment/382417/#Comment_382417

Thanks for the update, appreciated.  I have been keeping a hopeful eye on this thread ever since I posted my workaround.

**Comment by hoverdonkey** [comment] 2021-05-21 08:34
PS I am not very Windows literate, but I have a dim memory that spaces couldn't be used in MS-DOS or NTFS (unless quotation marks are used).  I wondered if the glitch could be happening somewhere down that road?

**Comment by adomasven** [comment] 2024-05-02 09:31
Closing for now and we can reopen if we still get reports.

**Closed by adomasven** 2024-05-02 09:31 UTC
